### ISSUE TITLE
update's dt is inconsistent between Game.pause and device lock

### ISSUE THREAD

**Issue by Nico04** [flame-engine/forge2d#78]
The update(dt) method gives `The time dt in seconds since the last update cycle`.
When the game is paused, it is expected that the update's `dt` time resumes were it was when game is resumed. So if the games pauses for 2min, the dt on resume will not be 2min or so.

This works perfectly fine when using the Game.pause field.
But if game is paused because device screen goes off, the dt time it inconsistent when screen goes on (it will be around 2min in my exemple).

**Comment by spydon** [comment]
Since the game doesn't have any information about the state of the device, this is up to the user to implement.

**Comment by Nico04** [comment]
I agree it's normal the Game doesn't know about de state of the device. But since the update isn't called when screen is off (like a proper pause), it shouldn't cause that issue neither, so for me this is kind of a bug, don't you think ?

**Comment by spydon** [comment]
The only contract that `update` follows is to call with delta time since the last update, and since it follows that I don't think it's really a bug. The user have to either pause the game or discard dts that are too large or produced directly after the device wakes up to remedy this I think. Or do you have any other sugeested solution for this?

**Comment by Nico04** [comment]
Well, if the only contracts is to give delta time since last update like you said, why it doesn't give the pause duration ?
If you make a 5min pause, it then should return approx 5min as dt, but it doesn't (which is good).
What I'm saying is that it doesn't look consistent to me.
As for a proposal, do you have any idea why it behave like that ? update is not called while screen off, like pause does, so where is the difference ?

**Comment by spydon** [comment]
Meanwhile the game is paused the `dt` will not increase, that is of course part of the contract too. The game isn't transitioned to the paused state meanwhile the screen is off, that is up to the user to handle currently, since the game is unaware of the state of the underlying device, meanwhile the user has the ability to handle that.
